Algoritmo "Tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/06/2025
Var

   x, y, i : inteiro

Inicio
      escreva ("Deseja a tabuada para qual valor?")
              leia (x)
      para i de 1 ate 10 faca
           y <- x * i
           escreval (x, " X", i, " =", y)
      fimpara
Fimalgoritmo